# Generated by Django 4.2.1 on 2025-03-15 05:01

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='notifications/', verbose_name='Фото/Аудиофайл/Видео')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
