# Generated by Django 4.2.1 on 2025-03-15 08:03

from django.db import migrations, models
import web.validators.file


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='notifications/', validators=[web.validators.file.FileValidator()], verbose_name='Фото/Аудиофайл/Видео'),
        ),
    ]
