# Generated by Django 4.2.1 on 2025-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='city',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
