# Generated by Django 4.2.1 on 2025-03-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_telegramuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
