# Generated by Django 4.2.1 on 2025-03-15 08:03

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('channel_link', models.URLField(verbose_name='Ссылка на канал')),
                ('manager_link', models.URLField(verbose_name='Ссылка на аккаунт менеджера')),
            ],
            options={
                'verbose_name': 'Ссылки',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
