# Generated by Django 4.2.1 on 2025-03-15 08:14

from django.db import migrations, models
import web.db.model_mixins
import web.validators.file


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessages',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('welcome_video', models.FileField(upload_to='bot_media/', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4',))], verbose_name='Приветственное видео')),
            ],
            options={
                'verbose_name': 'Сообщения бота',
                'verbose_name_plural': 'Сообщения бота',
            },
        ),
    ]
