# Generated by Django 4.2.1 on 2025-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0002_botmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessages',
            name='about_teacher_text',
            field=models.TextField(max_length=4000, verbose_name='Об учителе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botmessages',
            name='faq_text',
            field=models.TextField(max_length=4000, verbose_name='Ответы на вопросы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file',
            field=models.FileField(upload_to='', verbose_name='Видео/Фото отзывов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_text',
            field=models.TextField(max_length=4000, verbose_name='Отзывы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botmessages',
            name='society_text',
            field=models.TextField(max_length=4000, verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botmessages',
            name='useful_posts_text',
            field=models.TextField(max_length=4000, verbose_name='Полезные статьи'),
            preserve_default=False,
        ),
    ]
