# Generated by Django 4.2.1 on 2025-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0004_remove_botmessages_society_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessages',
            name='enter_info_text',
            field=models.TextField(default='Вводная информация', max_length=4000, verbose_name='Текст "Вводная информация"'),
            preserve_default=False,
        ),
    ]
