# Generated by Django 4.2.1 on 2025-04-04 14:35

from django.db import migrations, models
import web.validators.file


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0007_alter_botmessages_reviews_file_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessages',
            name='faq_text',
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_10',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 10'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_11',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 11'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_12',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 12'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_13',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 13'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_14',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 11'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_15',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 15'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 5'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 6'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_7',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 7'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_8',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 8'),
        ),
        migrations.AddField(
            model_name='botmessages',
            name='reviews_file_9',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов 9'),
        ),
    ]
