# Generated by Django 4.2.1 on 2025-04-07 11:08

from django.db import migrations, models
import web.db.model_mixins
import web.validators.file


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0008_remove_botmessages_faq_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotReview',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4', '.jpg', '.jpeg', '.png'))], verbose_name='Видео/Фото отзывов')),
            ],
            options={
                'verbose_name': 'Отзыв бота',
                'verbose_name_plural': 'Отзывы бота',
            },
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_1',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_10',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_11',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_12',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_13',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_14',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_15',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_2',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_3',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_4',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_5',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_6',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_7',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_8',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_file_9',
        ),
        migrations.RemoveField(
            model_name='botmessages',
            name='reviews_text',
        ),
    ]
