# Generated by Django 4.2.1 on 2025-04-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0009_botreview_remove_botmessages_reviews_file_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessages',
            name='welcome_text',
            field=models.TextField(default='', max_length=1000, verbose_name='Приветственный текст'),
        ),
    ]
