# Generated by Django 4.2.1 on 2025-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_alter_topic_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(choices=[('Technology', 'О технологии'), ('Post', 'Полезная информация')], default='Technology', max_length=30),
        ),
    ]
