# Generated by Django 4.2.1 on 2025-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_topic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(choices=[('Tech', 'О технологии'), ('Post', 'Полезная информация')], default='Tech', max_length=30, verbose_name='Раздел'),
        ),
    ]
