# Generated by Django 4.2.1 on 2025-04-03 14:28

from django.db import migrations, models
import web.db.model_mixins
import web.validators.file


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_alter_topic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4',))], verbose_name='Видео(mp4)')),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='', validators=[web.validators.file.FileValidator(allowed_extensions=('.jpg', '.jpeg', '.png'))], verbose_name='Фото(.jpg/.jpeg/.png)')),
                ('text', models.TextField(blank=True, default=None, max_length=900, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
