# Generated by Django 4.2.1 on 2025-04-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'О технологии / Полезная информация', 'verbose_name_plural': 'О технологии / Полезная информация'},
        ),
    ]
