# Generated by Django 4.2.1 on 2025-04-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_alter_topic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст'),
        ),
    ]
