# Generated by Django 4.2.1 on 2025-03-15 05:01

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meditations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='Текст')),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='meditations.meditation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
