# Generated by Django 4.2.1 on 2025-03-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_telegramuser_city'),
        ('reviews', '0002_alter_review_options_alter_review_meditation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='telegram_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='telegram_users.telegramuser', verbose_name='Пользователь'),
        ),
    ]
