# Generated by Django 4.2.1 on 2025-03-15 05:01

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='meditations/', verbose_name='Аудиофайл(mp3)')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
