# Generated by Django 4.2.1 on 2025-03-15 08:03

from django.db import migrations, models
import web.validators.file


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meditation',
            options={'verbose_name': 'Медитация', 'verbose_name_plural': 'Медитации'},
        ),
        migrations.AlterField(
            model_name='meditation',
            name='file',
            field=models.FileField(upload_to='meditations/', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp3',))], verbose_name='Аудиофайл(mp3)'),
        ),
    ]
