# Generated by Django 4.2.1 on 2025-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0002_alter_meditation_options_alter_meditation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
