# Generated by Django 4.2.1 on 2025-04-03 13:35

from django.db import migrations, models
import web.validators.file


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0003_alter_meditation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='file',
            field=models.FileField(upload_to='meditations/', validators=[web.validators.file.FileValidator(allowed_extensions=('.mp4',))], verbose_name='Видеофайл(mp4)'),
        ),
    ]
