# Generated by Django 4.2.1 on 2025-04-07 11:28

from django.db import migrations, models
import django.db.models.deletion
import web.db.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_telegramuser_full_name'),
        ('meditations', '0004_alter_meditation_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='Текст')),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='meditations.meditation', verbose_name='Медитация')),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв медитации',
                'verbose_name_plural': 'Отзывы медитаций',
            },
        ),
    ]
