# Generated by Django 4.2.1 on 2025-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='file_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='File id'),
        ),
    ]
