# Generated by Django 4.2.1 on 2025-04-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0007_alter_meditation_file_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meditation',
            options={'ordering': ['order'], 'verbose_name': 'Медитация', 'verbose_name_plural': 'Медитации'},
        ),
        migrations.AddField(
            model_name='meditation',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
