# Generated by Django 4.2.1 on 2025-04-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0008_alter_meditation_options_meditation_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meditation',
            options={'verbose_name': 'Медитация', 'verbose_name_plural': 'Медитации'},
        ),
    ]
