# Generated by Django 4.2.1 on 2025-03-15 08:03

from django.db import migrations, models
import web.db.model_mixins
import web.validators.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='topics/', validators=[web.validators.file.FileValidator()], verbose_name='Фото/Аудиофайл/Видео')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Медитация',
                'verbose_name_plural': 'Медитации',
            },
        ),
    ]
