# Generated by Django 4.2.1 on 2025-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='file',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='text',
        ),
        migrations.AddField(
            model_name='topic',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
